services:
  # Aplicação NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meupaozin-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=pedidos_db
      # Datadog Configuration
      - DD_SERVICE_NAME=meu-paozin-api
      - DD_ENV=development
      - DD_VERSION=1.0.0
      - DD_TRACE_ENABLED=true
      - DD_AGENT_HOST=datadog-agent
      - DD_AGENT_PORT=8126
      - DD_LOGS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_ANALYTICS_ENABLED=true
      - DD_LOG_INJECTION=true
      - DD_REPORT_HOSTNAME=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - meupaozin-network
    restart: unless-stopped

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: meupaozin-postgres
    environment:
      - POSTGRES_DB=pedidos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meupaozin-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  meupaozin-network:
    driver: bridge 