version: '3.8'

services:
  # Aplicação NestJS
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meupaozin-api-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=pedidos_db
    depends_on:
      - postgres
    networks:
      - meupaozin-network
    restart: unless-stopped

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: meupaozin-postgres-prod
    environment:
      - POSTGRES_DB=pedidos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meupaozin-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  meupaozin-network:
    driver: bridge 